export const EXERCISE_LIBRARY = [
  // ── Chest ────────────────────────────────────────────────
  { name: 'Barbell Bench Press',         muscle: 'Chest' },
  { name: 'Incline Barbell Bench Press', muscle: 'Chest' },
  { name: 'Decline Barbell Bench Press', muscle: 'Chest' },
  { name: 'Dumbbell Bench Press',        muscle: 'Chest' },
  { name: 'Incline Dumbbell Press',      muscle: 'Chest' },
  { name: 'Decline Dumbbell Press',      muscle: 'Chest' },
  { name: 'Dumbbell Fly',                muscle: 'Chest' },
  { name: 'Incline Dumbbell Fly',        muscle: 'Chest' },
  { name: 'Cable Fly',                   muscle: 'Chest' },
  { name: 'High Cable Fly',              muscle: 'Chest' },
  { name: 'Low Cable Fly',               muscle: 'Chest' },
  { name: 'Machine Chest Press',         muscle: 'Chest' },
  { name: 'Pec Deck',                    muscle: 'Chest' },
  { name: 'Push-ups',                    muscle: 'Chest' },
  { name: 'Wide Push-ups',               muscle: 'Chest' },
  { name: 'Dips (Chest)',                muscle: 'Chest' },
  { name: 'Landmine Press',              muscle: 'Chest' },

  // ── Back ─────────────────────────────────────────────────
  { name: 'Conventional Deadlift',       muscle: 'Back' },
  { name: 'Sumo Deadlift',               muscle: 'Back' },
  { name: 'Barbell Row',                 muscle: 'Back' },
  { name: 'Pendlay Row',                 muscle: 'Back' },
  { name: 'T-Bar Row',                   muscle: 'Back' },
  { name: 'Dumbbell Row',                muscle: 'Back' },
  { name: 'Cable Row',                   muscle: 'Back' },
  { name: 'Seated Cable Row',            muscle: 'Back' },
  { name: 'Lat Pulldown',                muscle: 'Back' },
  { name: 'Wide-Grip Lat Pulldown',      muscle: 'Back' },
  { name: 'Close-Grip Lat Pulldown',     muscle: 'Back' },
  { name: 'Pull-ups',                    muscle: 'Back' },
  { name: 'Chin-ups',                    muscle: 'Back' },
  { name: 'Neutral-Grip Pull-ups',       muscle: 'Back' },
  { name: 'Assisted Pull-ups',           muscle: 'Back' },
  { name: 'Machine Row',                 muscle: 'Back' },
  { name: 'Face Pulls',                  muscle: 'Back' },
  { name: 'Hyperextensions',             muscle: 'Back' },
  { name: 'Good Mornings',               muscle: 'Back' },
  { name: 'Rack Pull',                   muscle: 'Back' },

  // ── Shoulders ─────────────────────────────────────────────
  { name: 'Barbell Overhead Press',      muscle: 'Shoulders' },
  { name: 'Seated Dumbbell Press',       muscle: 'Shoulders' },
  { name: 'Standing Dumbbell Press',     muscle: 'Shoulders' },
  { name: 'Arnold Press',                muscle: 'Shoulders' },
  { name: 'Machine Shoulder Press',      muscle: 'Shoulders' },
  { name: 'Lateral Raise',               muscle: 'Shoulders' },
  { name: 'Cable Lateral Raise',         muscle: 'Shoulders' },
  { name: 'Front Raise',                 muscle: 'Shoulders' },
  { name: 'Rear Delt Fly',               muscle: 'Shoulders' },
  { name: 'Reverse Pec Deck',            muscle: 'Shoulders' },
  { name: 'Upright Row',                 muscle: 'Shoulders' },
  { name: 'Shrugs',                      muscle: 'Shoulders' },
  { name: 'Dumbbell Shrugs',             muscle: 'Shoulders' },

  // ── Biceps ───────────────────────────────────────────────
  { name: 'Barbell Curl',                muscle: 'Biceps' },
  { name: 'EZ-Bar Curl',                 muscle: 'Biceps' },
  { name: 'Dumbbell Curl',               muscle: 'Biceps' },
  { name: 'Hammer Curl',                 muscle: 'Biceps' },
  { name: 'Incline Dumbbell Curl',       muscle: 'Biceps' },
  { name: 'Concentration Curl',          muscle: 'Biceps' },
  { name: 'Cable Curl',                  muscle: 'Biceps' },
  { name: 'High Cable Curl',             muscle: 'Biceps' },
  { name: 'Preacher Curl',               muscle: 'Biceps' },
  { name: 'Machine Curl',                muscle: 'Biceps' },
  { name: 'Spider Curl',                 muscle: 'Biceps' },
  { name: 'Zottman Curl',                muscle: 'Biceps' },

  // ── Triceps ──────────────────────────────────────────────
  { name: 'Tricep Pushdown (Cable)',     muscle: 'Triceps' },
  { name: 'Rope Pushdown',               muscle: 'Triceps' },
  { name: 'Overhead Tricep Extension',   muscle: 'Triceps' },
  { name: 'Skull Crushers',              muscle: 'Triceps' },
  { name: 'Close-Grip Bench Press',      muscle: 'Triceps' },
  { name: 'Dips (Triceps)',              muscle: 'Triceps' },
  { name: 'Diamond Push-ups',            muscle: 'Triceps' },
  { name: 'Kickbacks',                   muscle: 'Triceps' },
  { name: 'JM Press',                    muscle: 'Triceps' },

  // ── Legs ─────────────────────────────────────────────────
  { name: 'Barbell Back Squat',          muscle: 'Legs' },
  { name: 'Front Squat',                 muscle: 'Legs' },
  { name: 'Goblet Squat',                muscle: 'Legs' },
  { name: 'Bulgarian Split Squat',       muscle: 'Legs' },
  { name: 'Leg Press',                   muscle: 'Legs' },
  { name: 'Hack Squat',                  muscle: 'Legs' },
  { name: 'Romanian Deadlift',           muscle: 'Legs' },
  { name: 'Stiff-Leg Deadlift',          muscle: 'Legs' },
  { name: 'Nordic Hamstring Curl',       muscle: 'Legs' },
  { name: 'Lying Leg Curl',              muscle: 'Legs' },
  { name: 'Seated Leg Curl',             muscle: 'Legs' },
  { name: 'Leg Extension',               muscle: 'Legs' },
  { name: 'Walking Lunges',              muscle: 'Legs' },
  { name: 'Reverse Lunges',              muscle: 'Legs' },
  { name: 'Step-ups',                    muscle: 'Legs' },
  { name: 'Hip Thrust',                  muscle: 'Legs' },
  { name: 'Glute Bridge',                muscle: 'Legs' },
  { name: 'Sumo Squat',                  muscle: 'Legs' },
  { name: 'Box Squat',                   muscle: 'Legs' },
  { name: 'Sissy Squat',                 muscle: 'Legs' },

  // ── Calves ───────────────────────────────────────────────
  { name: 'Standing Calf Raise',         muscle: 'Calves' },
  { name: 'Seated Calf Raise',           muscle: 'Calves' },
  { name: 'Leg Press Calf Raise',        muscle: 'Calves' },
  { name: 'Single-Leg Calf Raise',       muscle: 'Calves' },
  { name: 'Donkey Calf Raise',           muscle: 'Calves' },

  // ── Core ─────────────────────────────────────────────────
  { name: 'Plank',                       muscle: 'Core' },
  { name: 'Side Plank',                  muscle: 'Core' },
  { name: 'Cable Crunch',                muscle: 'Core' },
  { name: 'Crunches',                    muscle: 'Core' },
  { name: 'Decline Crunches',            muscle: 'Core' },
  { name: 'Hanging Leg Raise',           muscle: 'Core' },
  { name: 'Lying Leg Raise',             muscle: 'Core' },
  { name: 'Russian Twist',               muscle: 'Core' },
  { name: 'Ab Wheel Rollout',            muscle: 'Core' },
  { name: 'Dead Bug',                    muscle: 'Core' },
  { name: 'Dragon Flag',                 muscle: 'Core' },
  { name: 'Pallof Press',                muscle: 'Core' },
  { name: 'Woodchops',                   muscle: 'Core' },
  { name: 'L-Sit',                       muscle: 'Core' },
  { name: 'Toe Touches',                 muscle: 'Core' },
  { name: 'V-ups',                       muscle: 'Core' },
  { name: 'Mountain Climbers',           muscle: 'Core' },

  // ── Cardio ───────────────────────────────────────────────
  { name: 'Treadmill Run',               muscle: 'Cardio' },
  { name: 'Stationary Bike',             muscle: 'Cardio' },
  { name: 'Rowing Machine',              muscle: 'Cardio' },
  { name: 'Stair Climber',               muscle: 'Cardio' },
  { name: 'Elliptical',                  muscle: 'Cardio' },
  { name: 'Jump Rope',                   muscle: 'Cardio' },
  { name: 'Sprint Intervals',            muscle: 'Cardio' },
  { name: 'Battle Ropes',                muscle: 'Cardio' },
  { name: 'Box Jumps',                   muscle: 'Cardio' },
  { name: 'Burpees',                     muscle: 'Cardio' },
  { name: 'Sled Push',                   muscle: 'Cardio' },
  { name: 'Assault Bike',                muscle: 'Cardio' },
]

export const MUSCLE_GROUPS = [
  'All', 'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Legs', 'Calves', 'Core', 'Cardio',
]
